name: Deploy Cricket Game

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        
    - name: Build Summary
      run: |
        echo "✅ Cricket Challenge 3D deployed successfully!"
        echo "🏏 Game is live at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
